### ISSUE TITLE
2.1.20 compatibility

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-keep-model-in-add-cards#1]
The combination of this add-on ("Keep model of add cards") and [Opening the same window multiple time](https://ankiweb.net/shared/info/354407385) doesn't work in 2.1.20 beta for me. 

I think it's because of the commit https://github.com/ankitects/anki/commit/89fce1f6b7ed0ff25be793b982efd8b8e878c653# which changed the method `onModelChange` of the class AddCards.

I noticed because this also breaks [Quick note and deck buttons](https://ankiweb.net/shared/info/1331140127) which I ported to 2.1 and adjusted to work with your add-on "Keep model of add cards". I dread looking into this although the "Quick note" add-on is one of the most downloaded ones I released ... At the moment I hope that you are still interested in these add-ons and fix "Keep Models" so that I can take inspiration from your code ....

**Comment by Arthur-Milchior** [comment]
Thank you very much for letting me know. Can you please tell me:
1. what error message you had (assuming there is one)
2. what you tried to do when you found the problem and what occurred. So that I can understand how to reproduce it.

**Comment by ijgnd** [comment]
Sorry for an incomplete report. Now I have trouble reproducing it. That's slightly embarrassing. I'll get back on the weekend when I have more time.

**Comment by Arthur-Milchior** [comment]
Take your time. No worry.
For the context: I've already had to deal with 5 add-ons which were incompatible with 2.1.20, so I really want to have as complete report as possible because it already takes far too much of my time

**Comment by Arthur-Milchior** [comment]
Was it 
`Caught exception:
Traceback (most recent call last):
  File "/home/arthur/.local/share/Anki2/addons21/424778276/keepModelInAddCards.py", line 69, in onModelChange
    self.onModelChange() #this is onModelChange from card, and note from ModelChange
TypeError: onModelChange() missing 1 required positional argument: 'unused'`

?

In this case, I'll submit a PR to anki instead of editing my add-on.

**Comment by ijgnd** [comment]
Yes, on Tuesday I had the error `TypeError: onModelChange() missing 1 required positional argument: 'unused'`. Thanks for looking into this.

**Comment by Arthur-Milchior** [comment]
Good news, it's corrected.
Bad news, you won't have the correction until the next beta.
I believe that you can safely deactivate this add-on. It should not be a big problem if we don't have it during a few weeks

**Comment by ijgnd** [comment]
I forgot to close this. Thanks for your quick fix.
