### ISSUE TITLE
Issuse report

### ISSUE THREAD

**Issue by havewisdom** [Arthur-Milchior/anki-keep-model-in-add-cards#3]
<img width="578" alt="스크린샷 2020-05-03 오전 10 29 07" src="https://user-images.githubusercontent.com/62235227/80896530-4096f800-8d2a-11ea-859b-d55ea86f26b2.png">

Thank you for your effort!.
your add-on really help me

**Comment by Arthur-Milchior** [comment]
you'll probably need to remove it and install it again

**Comment by havewisdom** [comment]
> you'll probably need to remove it and install it again

Oh it soloved..
Thank you for your advice.
have a good weekend
