### ISSUE TITLE
model not kept (latest versions from 2020-05-16)

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-keep-model-in-add-cards#6]
I just tested with 2.1.26 from ankiweb (and also from a cloned github repo) on linux in a new profile with just latest versions of the add-ons [Opening the same window multiple time](https://ankiweb.net/shared/info/354407385) and [Keep model of add cards](https://ankiweb.net/shared/info/424778276) installed.

When I have two "Add" windows open now changing the note type in one also changes the note type in another. 

I think I didn't make a mistake when using the add-ons:

![](https://raw.githubusercontent.com/ijgnd/anki__help/master/screenshots/keep_multiple.gif)

Thanks for creating & maintaining these add-ons.

**Comment by Arthur-Milchior** [comment]
Thanks for making such a clear bug report.
You clearly didn't make a mistake. I'll be looking into it.

**Comment by Arthur-Milchior** [comment]
Please try to update

**Comment by ijgnd** [comment]
It works. Thank you very much for this fix at lightning speed.

**Comment by Arthur-Milchior** [comment]
Just look at https://github.com/Arthur-Milchior/anki-keep-model-in-add-cards/commit/f2be30c9b4a858cf037c24823deb974736dcb7d0
You'll understand why it could be so quick :p
